language: python

matrix:
  include:
    - sudo: required
      services:
        - docker
      env:
        - RELEASE=trusty
    - sudo: required
      env:
        - RELEASE=precise

env:
  global:
    - VERSION='3.5.0'
    - ALIAS='3.5'

install:
  - if [ -z "$VERSION" ]; then echo "\$VERSION not defined" && travis_terminate 2; fi
  - pushd /opt/pyenv/
  - sudo git checkout master
  - sudo git pull
  - popd

before_script:
  - 'export INSTALL_DEST=${INSTALL_DEST:-/opt/python}'
  - 'export LSB_RELEASE=${LSB_RELEASE:-$(lsb_release -rs)}'
  - 'export PACKAGES=${PACKAGES:-pip numpy nose pytest mock wheel}'

script: ./build-python

after_success: ./create-archive

after_failure:
  - cat /tmp/python-build.*.log

addons:
  artifacts:
    paths:
    - $LSB_RELEASE/
    target_paths:
    - /$LSB_RELEASE
