language: python

matrix:
  include:
    - sudo: required
      services:
        - docker
      env:
        - RELEASE=trusty
    - sudo: required
      env:
        - RELEASE=precise

env:
  global:
    - VERSION='3.6-dev'
    - ALIAS='nightly'
    - INSTALL_DEST=/opt/python
    - PACKAGES='pip numpy nose pytest mock wheel'

install:
  - pushd /opt/pyenv/
  - sudo git checkout master
  - sudo git pull
  - popd

script:
  - pushd $HOME
  - sudo env PYTHON_BUILD_ROOT=/opt/pyenv/plugins/python-build /opt/pyenv/plugins/python-build/bin/python-build $VERSION $INSTALL_DEST/$VERSION
  - sudo ln -s $INSTALL_DEST/$VERSION $INSTALL_DEST/$ALIAS
  - virtualenv --distribute --python=$INSTALL_DEST/$VERSION/bin/python /home/travis/virtualenv/python$VERSION
  - ln -s $HOME/virtualenv/python$VERSION $HOME/virtualenv/python$ALIAS
  - $HOME/virtualenv/python$VERSION/bin/pip install --upgrade $PACKAGES
  - popd

after_success:
  - mkdir $HOME/archive/$(lsb_release -rs)
  - tar cjf $HOME/archive/$(lsb_release -rs)/python-$ALIAS.tar.bz2 $INSTALL_DEST/$VERSION $INSTALL_DEST/$ALIAS $HOME/virtualenv/python$VERSION $HOME/virtualenv/python$ALIAS
  - ls -lh $HOME/archive/$(lsb_release -rs)/python-$ALIAS.tar.bz2

after_failure:
  - cat /tmp/python-build.*.log

deploy:
  provider: s3
  access_key_id: $ARTIFACTS_KEY
  secret_access_key: $ARTIFACTS_SECRET
  bucket: $ARTIFACTS_BUCKET
  local_dir: $HOME/archive/$(lsb_release -rs)
  on:
    all_branches: true
  acl: public_read
