language: python

matrix:
  include:
    - sudo: required
      services:
        - docker
      env:
        - RELEASE=trusty
    - sudo: required
      env:
        - RELEASE=precise
    - os: osx
      env:
        - RELEASE=mavericks

env:
  global:
    - VERSION='3.6-dev'
    - ALIAS='nightly'

install:
  - pushd /opt/pyenv/
  - sudo git checkout master
  - sudo git pull
  - popd

before_script:
  - 'export INSTALL_DEST=${INSTALL_DEST:-/opt/python}'
  - export LSB_RELEASE=$(lsb_release -rs 2>/dev/null || sw_vers -productVersion | sed 's/^\([0-9][0-9]*.[0-9][0-9]*\).*/\1/')'
  - 'export OS_NAME=${OS_NAME:-$((lsb_release -is || echo "osx") | tr "A-Z" "a-z")}'
  - 'export ARCH=${ARCH:-$(uname -m)}'
  - 'export PACKAGES=${PACKAGES:-pip numpy nose pytest mock wheel}'

script: ./build-python

after_success: ./create-archive

after_failure:
  - cat /tmp/python-build.*.log

addons:
  artifacts:
    paths:
    - $LSB_RELEASE/
    target_paths:
    - /binaries/$OS_NAME/$LSB_RELEASE/$ARCH
