language: python

matrix:
  include:
    - sudo: required
      services:
        - docker
      env:
        - RELEASE=trusty
    - sudo: required
      env:
        - RELEASE=precise
    - language: c
      os: osx
      osx_image: xcode8.2
      env:
        - RELEASE=sierra
    - language: c
      os: osx
      osx_image: xcode7.3
      env:
        - RELEASE=elcapitan
    - language: c
      os: osx
      osx_image: xcode6.4
      env:
        - RELEASE=yosemite

env:
  global:
    - VERSION='3.7-dev'
    - ALIAS='nightly'

install:
- |
  if [[ "$(uname)" == "Linux" ]] ; then
    pushd /opt/pyenv/
    sudo git checkout master
    sudo git pull
    popd
  else
    brew uninstall pyenv
    brew install pyenv --HEAD
  fi
  if ! python -m pip >&/dev/null; then
    wget https://bootstrap.pypa.io/get-pip.py
    sudo python get-pip.py
  fi
- sudo -H python -m pip install virtualenv --upgrade

before_script:
- 'export INSTALL_DEST=${INSTALL_DEST:-/opt/python}'
- export LSB_RELEASE=$(lsb_release -rs 2>/dev/null || sw_vers -productVersion | sed 's/^\([0-9][0-9]*.[0-9][0-9]*\).*/\1/')
- 'export OS_NAME=$((lsb_release -is 2>/dev/null || echo "osx") | tr [[:upper:]] [[:lower:]])'
- 'export ARCH=${ARCH:-$(uname -m)}'
- 'export PACKAGES=${PACKAGES:-pip nose pytest mock wheel}'
- export PYTHON_CONFIGURE_OPTS="--with-wide-unicode --enable-shared --enable-ipv6 --enable-loadable-sqlite-extensions --with-computed-gotos $CONFIGURE_OPTS"

script: ./bin/compile

after_success: ./bin/archive

after_failure: cat /tmp/python-build.*.log

addons:
  apt:
    packages:
      - openssl
  artifacts:
    paths:
    - $LSB_RELEASE/
    target_paths:
    - /binaries/$OS_NAME/$LSB_RELEASE/$ARCH

